exit code 1 the action if the vrt test failed

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -10,7 +10,6 @@ inputs:
     type: string
     required: true
 
-
 runs:
   using: composite
   steps:
@@ -54,7 +53,7 @@ runs:
       working-directory: ${{ github.action_path }}
       shell: bash
       run: |
-        # we dont want to halt on an error since backstop test might fail and that's ok
+        # we dont want to halt on an error since backstop test might fail and we want to store the reports
         set +e
         suppress=$(./node_modules/.bin/backstop test)
         
@@ -87,3 +86,12 @@ runs:
         path: |
           ${{ github.action_path }}/backstop_data
           !${{ github.action_path }}/backstop_data/engine_scripts/*
+
+    - name: Return Results
+      id: return-results
+      if: ${{ always() }}
+      shell: bash
+      run: |
+        if [[ "false" = "${{ env.vrt_results }}" ]]; then
+          exit 1;
+        fi
